# Generated by Django 4.2.2 on 2023-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimonial', models.TextField()),
                ('picture', models.ImageField(upload_to='testimonials/')),
                ('rating', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
