# Generated by Django 4.2.2 on 2023-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_testimonial_alter_emp_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('rating', models.IntegerField(max_length=1)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
